# Preparing weight batches for MORL

Playground code for 

In [1]:
import numpy as np
import torch

In [16]:
BATCH_SIZE = 5
WEIGHT_NUM = 2
REWARD_SIZE = 3
FloatTensor = torch.FloatTensor

In [17]:
w_batch = np.random.randn(WEIGHT_NUM, REWARD_SIZE); w_batch

array([[ 0.85627939, -0.10515328, -1.70294526],
       [-1.67505533,  0.45567369,  0.91296971]])

In [18]:
w_batch = np.abs(w_batch) / np.linalg.norm(w_batch, ord=1, axis=1, keepdims=True); w_batch

array([[0.3213806 , 0.03946635, 0.63915304],
       [0.55033546, 0.14971051, 0.29995403]])

In [19]:
w_batch = torch.from_numpy(w_batch.repeat(BATCH_SIZE, axis=0)).type(torch.FloatTensor)

In [20]:
w_batch

tensor([[0.3214, 0.0395, 0.6392],
        [0.3214, 0.0395, 0.6392],
        [0.3214, 0.0395, 0.6392],
        [0.3214, 0.0395, 0.6392],
        [0.3214, 0.0395, 0.6392],
        [0.5503, 0.1497, 0.3000],
        [0.5503, 0.1497, 0.3000],
        [0.5503, 0.1497, 0.3000],
        [0.5503, 0.1497, 0.3000],
        [0.5503, 0.1497, 0.3000]])